#!/bin/bash

# Source this file to run the simulation
# (currently PWD needs to be accel-sim-framework)
# Need to provide parameters like below

# Example:
# source test_run.sh util/tuner/RTX2080_S/dlt gpu-simulator/gpgpu-sim/configs/tested-cfgs/RTX2080_S RTX2080_S cuDGT test0

source_dir="$1"     # Directory of expanded & indexed configs generated by apply_parsed_deltas() from test_configs.ipynb
target_dir="$2"     # Directory of the simulation's GPU config file (located within gpgpu-sim)
cfg="$3"            # Name of the config (defined in util/job_launching/configs/define-standard-cfgs.yml)
benchmark="$4"      # Name of the benchmark (defined in util/job_launching/apps/define-all-apps.yml)
prefix="$5"         # Any custom prefix you'd like to append

# Save original config
cp "$target_dir/gpgpusim.config" "$target_dir/gpgpusim.original.config"

for filename in "$source_dir"/*.config; do
  # Extract ID
  id=${filename%.config}
  echo "Running ${id##*/}"

  # Put config in simulation & run simulation
  cp "$filename" "$target_dir/gpgpusim.config"
  ./util/job_launching/run_simulations.py \
    -T ./hw_run/traces/device-0/11.6/ \
    -C "$cfg" -N "$prefix-$benchmark-${id##*/}" -B "$benchmark"

  # Sleep to not overload the job_launching
  sleep 3
done

# Restore original config
mv "$target_dir/gpgpusim.original.config" "$target_dir/gpgpusim.config"