#!/bin/bash

# Source this file to get status of all the running simulations
# (currently PWD needs to be accel-sim-framework)
# Need to provide parameters like below

source_dir="$1"     # Directory of expanded & indexed configs generated by apply_parsed_deltas() from test_configs.ipynb
benchmark="$2"      # Name of the benchmark (defined in util/job_launching/apps/define-all-apps.yml)
prefix="$3"         # Custom prefix appended in test_run.sh

for filename in "$source_dir"/*.config; do
  id=${filename%.config}
  echo "Status of ${id##*/}"
  ./util/job_launching/job_status.py -N "$prefix-$benchmark-${id##*/}"
done